
(add-hook 'python-mode-hook
	  (lambda()
	    (local-set-key (kbd "<C-return>")
			   (lambda ()
			     (interactive)
			     (py-execute-line)
			     (next-line)))
	    (local-set-key (kbd "C-n")
			   (lambda ()
			     (interactive)
			     (py-execute-line)
			     (next-line)))
	    (local-set-key (kbd "<M-return>")
			   (lambda ()
			     (interactive)
			     (py-execute-region)
			     (py-switch-to-shell)))
	    (local-set-key (kbd "M-n")
			   (lambda ()
			     (interactive)
			     (py-execute-region)
			     (py-switch-to-shell)))
	    (local-set-key (kbd "C-M-n") 'py-execute-buffer)))

